### ISSUE TITLE
Vim command mode cursor invisible

### ISSUE THREAD

**Issue by boomskats** [zcysxy/Obsidian-Terminal-Theme#1]
Mate this is absolutely the most beautiful of beautiful Obsidian themes. But I think it might be broken in terms of vim command mode  :-o  at least with the version of Codemirror (6?) which I think my version of Obsidian rocks (0.13.16)

I'm gonna have a go at fixing it

![terminalthemevim](https://user-images.githubusercontent.com/11962123/147519662-c4cad4f4-3066-4e63-80fc-7dc143e6b506.gif)

**Comment by zcysxy** [comment]
Thanks for reporting this bug! Since I don't use vim in Obsidian, it might take me a while to fix this. Feel free to make a pull request if you have a fix :)

**Comment by Tiriyon** [comment]
Similar issue here
I will have a look on the code and If I can manage I will PR.
![image](https://user-images.githubusercontent.com/52870466/183059746-8c3daea1-2cdf-4f94-a2f1-eeb8774aa5ac.png)

**Comment by zcysxy** [comment]
Finally solved this issue. Huge thanks to @pseudometa
