### ISSUE TITLE
Suddenly it restarted Obsidian.

### ISSUE THREAD

**Issue by Tripeshor** [zcysxy/Obsidian-Terminal-Theme#12]
Hi, i've been using the  theme for a week now, tonight while I was working on my browser Obsidian collapsed, restarted the opened vaults I had, the Terminal's Vauls appeared with the default theme, and unistalled.

**Comment by zcysxy** [comment]
Hi, this issue is unrelated to any specific theme. It could be due to interference from plugins or an Obsidian bug.
