### ISSUE TITLE
Ability to full screen 

### ISSUE THREAD

**Issue by lathomas64** [zcysxy/Obsidian-Terminal-Theme#2]
It appears that the window controls to full screen obsidian in this terminal are all gone. Suggestion to include an alternative to trying to drag the corners to get your terminal theme obsidian to full screen or, if such a method already exists make it somehow more prominent or include it in the readme.

**Comment by zcysxy** [comment]
I'm not sure I get what you mean. What operating system are you on? If you mean to drag the Obsidian window to change its size, then it works fine on my end.

https://user-images.githubusercontent.com/48207708/165030920-3e92586d-ea71-4ae3-b699-fe33dbd45c98.mp4

Or do you mean to collapse sidebars to make the center pane full screen? If so you need to use commands (`toggle left sidebar` and `toggle right sidebar`) or hotkeys. Yeah this theme assumes you are familiar with Obsidian commands. I'll make it clear in the README

**Comment by zcysxy** [comment]
Close for now.
