### ISSUE TITLE
It's hard to find Preferences settings

### ISSUE THREAD

**Issue by fcastro97** [zcysxy/Obsidian-Terminal-Theme#3]
I need help, is difficult to find the settings

**Comment by zcysxy** [comment]
There should be a gear icon for settings at the bottom left corner. Also you can hit `ctrl/cmd` + `,` to open the settings

**Comment by chenshaolang** [comment]
The gear icon could not be found ......

**Comment by zcysxy** [comment]
> The gear icon could not be found ......

Hi @chenshaolang, could you test it in the sanbox vault? It looks like this on macOS:

<img width="224" alt="image" src="https://user-images.githubusercontent.com/48207708/175250002-bcbca214-0943-4416-adb7-7d50a7ffbda6.png">

Which os are you using?
