### ISSUE TITLE
important quetsio,

### ISSUE THREAD

**Issue by joorso** [zcysxy/Obsidian-Terminal-Theme#4]
hi !
 I am a newbie at obsidian so I tried all the theme for fun, but since I go on "Terminal obsidian" I can't get out  because I can't find the settings.

thanks for helping

**Comment by zcysxy** [comment]
Hi, there's a gear icon ⚙️ at the Left bottom corner. Or you can use hot key `Carl/Cmd` + `,`

**Comment by zcysxy** [comment]
Could you post a screenshot if you don’t see the gear icon?

**Comment by joorso** [comment]
thanks you so much the key worked, but there was not gear icon 

<img width="985" alt="Screenshot 2022-07-26 at 20 05 33" src="https://user-images.githubusercontent.com/110035934/181079514-0ac37c4d-12d4-498a-bc74-7add447e4778.png">

**Comment by zcysxy** [comment]
It's very weird. I'm also on macOS, and it's there 😵‍💫

<img width="1180" alt="image" src="https://user-images.githubusercontent.com/48207708/181182545-7bc6d5b4-7cbb-4c6b-aef8-f0e25a7bd7d3.png">
