### ISSUE TITLE
Please add support for block quote indent borders. 

### ISSUE THREAD

**Issue by distbit0** [zcysxy/Obsidian-Terminal-Theme#6]
Hi I really like this theme, thanks for making it.

I use block quotes (i.e. text prefixed with >) quite a lot when replying in obsidian to things people have written. 

Was wondering if you could add support for rendering them, as they are rendered in the default obsidian theme with outlines/borders delineating each indent level.

This would be extremely useful, and would make it much easier to view multi-level conversations using your theme.

This thread goes into a bit more detail with examples of how this should look: https://forum.obsidian.md/t/live-preview-improve-support-for-nested-quote-blocks/43824/4

It is hopefully just a couple of css lines, but I would not know. 

Many thx!

**Comment by zcysxy** [comment]
Thanks for the feedback! I added an indicator for block quotes. Please update the theme and let me know if it's not enough :)

**Comment by distbit0** [comment]
Hey thanks so much for implementing this so quickly @zcysxy. Have just updated on my end. Will let you know how it goes once I edit some heavily block quoted docs :) Many thx

**Comment by distbit0** [comment]
Hey @zcysxy I was wondering if you would be willing to also add block-quote indicators to lines which are wrapped, and aren't actually true/independent lines. 

This would be very helpful as I have found that when I view large documents with multi level block quotes, a lot of lines containing long sentences end up being wrapped around, which makes the indentation levels very unclear/un-crisp and hard to tell at a glance, which is the primary reason block quote indicator lines are useful :)

I also created this thread a while back in the obsidian forum on exactly this issue: https://forum.obsidian.md/t/live-preview-improve-support-for-nested-quote-blocks/43824

Only recently did the default obsidian editor add support for block quote indicators for wrapped lines, and lots of examples/extra details can be found in the above thread.

Thank you so much for this. I really enjoy the vibes of your theme.

**Comment by zcysxy** [comment]
Hi @distbit0, I reverted to the original Obsidian style, which takes care of the wrapped block quotes.

**Comment by distbit0** [comment]
Awesome thanks so much, that is perfect @zcysxy :)

**Comment by distbit0** [comment]
Hi @zcysxy would you mind also enabling indent indicators in the reading mode? 😅 

Really appreciate all of this help. Many thx
