### ISSUE TITLE
ios top menu

### ISSUE THREAD

**Issue by intmainreturn00** [zcysxy/Obsidian-Terminal-Theme#7]
- Hi, great theme ❤️ works especially nice with [ninja cursor](https://publish.obsidian.md/hub/02+-+Community+Expansions/02.05+All+Community+Expansions/Plugins/ninja-cursor#Ninja%20Cursor). 🥷
- The only problem for me is that every time I switch to it on desktop, I then stuck at mobile without ability to easy edit - can't tap on ✍️
    - ![telegram-cloud-photo-size-2-5458822078401727605-y|20](https://github.com/zcysxy/Obsidian-Terminal-Theme/assets/1473995/99d4b2de-c0b6-4cfc-8af9-111091eb4574)

**Comment by zcysxy** [comment]
Hi, thanks for using this theme. This theme currently does not support mobile devices. Are you able to switch to other themes on your mobile device?
