### ISSUE TITLE
Cursor not visible when in "normal mode" with "Vim key bindings"

### ISSUE THREAD

**Issue by drjackyl** [zcysxy/Obsidian-Terminal-Theme#8]
I'm using Vim key bindings and from time to time, I enjoy that hacky feeling of the Terminal theme. And I think Vim key bindings and the Terminal theme are a great fit :-) 

Though, when in normal mode, the cursor is not visible on the currently focused tab for me. As soon as I enter "insert mode", I see it. And on other visible (split) tabs, I can also see it.

To reproduce it, I'd say, enable Vim key bindings and activate the theme. When opening a file, you should then not see a cursor  unless you type `i` for insert mode.

Regards,
Felix

**Comment by zcysxy** [comment]
Hi, have you tried updating the theme? I cannot reproduce the issue.

**Comment by drjackyl** [comment]
Hm. Just yesterday, I updated and wrote the issue after I still had the problem. I was using dark mode on macOS. I'll check again later today.

**Comment by drjackyl** [comment]
Hi, sorry for the fuzz. I should have tested more. I deleted the theme from `./obsidian/themes`, reinstalled it and everything is fine, issue is gone.
